# Generated by Django 5.1.5 on 2025-03-04 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('skills', models.CharField(blank=True, max_length=500, verbose_name='Навыки')),
                ('experience', models.IntegerField(verbose_name='Опыт работы (в месяцах)')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('match_percentage', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=10)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vacancy')),
            ],
        ),
    ]
