# Generated by Django 5.1.5 on 2025-03-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('interview', 'На интервью'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=15),
        ),
    ]
