# Generated by Django 5.1.5 on 2025-03-05 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_candidateresume_missing_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
