# Generated by Django 5.1.5 on 2025-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_candidateresume_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='gpt_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
