# Generated by Django 5.1.5 on 2025-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_candidateresume_gpt_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
